routes/web.php
<?php

Route::get('/', 'Auth\LoginController@showLoginForm');

Route::post('login', 'Auth\LoginController@login')->name('login');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('dashboard', 'DashBoardController@index')->name('dashboard');
//
// Rutas correspondientes a los catálogos
//
Route::resource('areas', 'AreaController');

Route::resource('asignaturas', 'SubjectController');

Route::resource('partidas', 'DepartureController');

Route::resource('unidades', 'UnitController');

Route::resource('categorias', 'CategoryController');

Route::resource('marcas', 'BrandController');

Route::resource('modelos', 'ExemplarController');

Route::resource('tipos', 'TypeController');

Route::resource('materiales', 'MaterialController');

Route::resource('stock', 'StockController');
//
// Rutas para las requisiciones
//
Route::get('requisiciones', 'RequisitionController@index')->name('requisiciones.index');

Route::get('requisiciones/crear', 'RequisitionController@create')->name('requisiciones.crear');

Route::post('requisiciones/guardar', 'RequisitionController@store')->name('requisiciones.guardar');

Route::get('requisiciones/{requisicion}', 'RequisitionController@assign')->name('requisiciones.asignar');

Route::post('requisiciones/detalles', 'RequisitionController@storeDetails')->name('requisiciones.detalles.guardar');

Route::delete('requisiciones/{requisicion}', 'RequisitionController@destroy')->name('requisiciones.eliminar');

Route::get('requisiciones/imprimir/{requisicion}', 'RequisitionController@excel')->name('requisiciones.imprimir');

Route::get('requisiciones/enviar/{requisicion}', 'RequisitionController@sendRequisition')->name('requisiciones.enviar');

Route::get('requisiciones/recepcionar/{requisicion}', 'RequisitionController@receive')->name('requisiciones.recepcionar');

Route::post('requisiciones/recepcionar/detalles', 'RequisitionController@storeDetailsReceive')->name('recepcionar.guardar');

Route::get('requisiciones/{requisicion}/detalles/{detail}', 'RequisitionController@details')->name('requisiciones.detalles.almacen');

Route::post('requisiciones/detalles/almacen', 'RequisitionController@pullItemToStock')->name('requisiciones.almacen.guardar');

Route::get('requisiciones/download/{requisicion}', 'RequisitionController@downloadQR')->name('requisiciones.download');
//
// Rutas para solicitud de laboratorio
//
Route::get('solicitudes', 'RequestLaboratoriesController@index')->name('solicitudes.index');

Route::get('solicitudes/crear', 'RequestLaboratoriesController@create')->name('solicitudes.crear');

Route::post('solicitudes', 'RequestLaboratoriesController@addEvent')->name('solicitudes.añadir');

Route::delete('solicitudes/{solicitud}', 'RequestLaboratoriesController@destroy')->name('solicitudes.eliminar');

Route::get('solicitudes/aceptar/{requisicion}', 'RequestLaboratoriesController@acceptRequest')->name('solicitudes.aceptar');
//
// Rutas para prestamo de materiales
//
Route::get('prestamos', 'LoanController@index')->name('prestamos.index');

Route::get('prestamos/crear', 'LoanController@create')->name('prestamos.crear');

Route::delete('prestamos/{prestamo}', 'LoanController@destroy')->name('prestamos.eliminar');

Route::post('prestamos/guardar', 'LoanController@store')->name('prestamos.guardar');

Route::get('prestamos/{prestamo}', 'LoanController@assign')->name('prestamos.asignar');

Route::post('prestamos/detalles', 'LoanController@storeDetails')->name('prestamos.detalles.guardar');

Route::get('prestamos/enviar/{prestamo}', 'LoanController@sendLoan')->name('prestamos.enviar');

Route::get('prestamos/ver/{prestamo}', 'LoanController@seeLoan')->name('prestamos.ver');

Route::get('prestamos/devolver/{prestamo}', 'LoanController@sendBack')->name('prestamos.devolver');

Route::get('prestamos/recibir/{prestamo}', 'LoanController@receive')->name('prestamos.recibir');

Route::post('prestamos/recibir/almacenar', 'LoanController@stockMaterials')->name('prestados.almacenar');

Route::post('prestamos/ver/guardar', 'LoanController@storeLoanMaterials')->name('prestados.guardar');

Route::post('prestamos/devolver/guardar', 'LoanController@returnMaterial')->name('prestados.devolver.guardar');

Route::get('prestamos/prestados/{prestamo}', 'LoanController@seeLoanApproved')->name('aprobados.ver');

//Route::get('requisiciones/{id}', 'RequisitionController@show')->name('products.show')->middleware('permission:products.show');

//Route::get('requisiciones/editar/{id?}',['as'=>'editarrequisicion', 'uses' => 'RequisitionController@showRequisition'])->where('id_grupo', "[0-9]+");

app/Stock.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    protected $fillable = [
		'serial',
		'stock',
		'expiration',
		'requisition_id',
		'material_id'
	];

    public function material()
    {
        return $this->belongsTo('App\Material');
    }
}

app/Http/Controllers/StockController.php
<?php

namespace App\Http\Controllers;

use App\Stock;
use App\Category;
use App\Material;
//use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class StockController extends Controller
{
	public function __construct(){
    	$this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
    	
        $stocks = Stock::orderBy('material_id', 'asc')->latest()->paginate(7);

    	/*$stocks = DB::table('stocks')
        	->leftJoin('materials', 'stocks.material_id', '=', 'materials.id')
            ->leftJoin('types', 'materials.type_id', '=', 'types.id')
            ->leftJoin('units', 'materials.unit_id', '=', 'units.id')
        	->leftJoin('categories', 'materials.category_id', '=', 'categories.id')
        	->leftJoin('brands', 'materials.brand_id', '=', 'brands.id')
        	->select('stocks.*', 'materials.model', 'types.name as type', 'units.name as unit', 'brands.name as brand')
        	->orderBy('categories.id')
            ->get();*/


        /*$stocks = DB::table('stocks')
            ->leftJoin('materials', 'stocks.material_id', '=', 'materials.id')
            ->leftJoin('types', 'materials.type_id', '=', 'types.id')
            ->leftJoin('units', 'materials.unit_id', '=', 'units.id')
            ->leftJoin('categories', 'materials.category_id', '=', 'categories.id')
            ->leftJoin('brands', 'materials.brand_id', '=', 'brands.id')
            ->select('stocks.*', 'materials.*', 'types.name as type', 'units.name as unit', 'categories.name as category', 'brands.name as brand')
            ->where('categories.id', '=', $id)
            ->get();*/

        return view('stock.index', compact('categories', 'stocks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $materials = Material::all();

        return view('stock.crear', compact('categories','materials'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        
        $request->validate([
            'serial'=>'required|max:100',
        ]);

        $material = new Stock([
            'serial' => $request->get('serial'),
            'expiration' => $request->get('expiration'),
            'material_id' => $request->get('material_id')
        ]);

        $material->save();
        
        return redirect('/stock')
        ->with('successed', 'El material se registró exitasamente en el stock!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $itemStock = Stock::find($id);
        /*$stocks = DB::table('stocks')
            ->leftJoin('materials', 'stocks.material_id', '=', 'materials.id')
            ->leftJoin('types', 'materials.type_id', '=', 'types.id')
            ->leftJoin('units', 'materials.unit_id', '=', 'units.id')
            ->leftJoin('categories', 'materials.category_id', '=', 'categories.id')
            ->leftJoin('brands', 'materials.brand_id', '=', 'brands.id')
            ->select('stocks.*', 'materials.*', 'types.name as type', 'units.name as unit', 'categories.name as category', 'brands.name as brand')
            ->where('categories.id', '=', $id)
            ->get();*/

        return view('stock.show',compact('itemStock'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $material = Stock::find($id);
        $categories = Category::all();
        $brands = Brand::all();
        $exemplars = Exemplar::all();

        return view('stock.editar', compact('material','categories','brands','exemplars'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required|max:80',
            'key'=>'required|max:50',
            'code'=>'required|integer|min:1|max:99999999999',
            'description'=> 'max:300',
            'category_id'=>'required',
            'brand_id'=>'required',
            'exemplar_id'=>'required'
        ]);

        $material = Stock::find($id);
        $material->name = $request->get('name');
        $material->key = $request->get('key');
        $material->code = $request->get('code');
        $material->description = $request->get('description');
        $material->category_id = $request->get('category_id');
        $material->brand_id = $request->get('brand_id');
        $material->exemplar_id = $request->get('exemplar_id');
        $material->save();

        return redirect('/stock')
            ->with('successed', 'El material se modificó exitasamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $material = Stock::find($id);
        $material->delete();

        return redirect('/stock')->with('successed', 'El material se eliminó exitasamente del stock!');
	}
}

resources/views/stock/crear.blade.php
@extends('dashboard')

@section('content')

<div class="box box-solid box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Almacenar material</h3>
    <div class="box-tools pull-right">
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <form method="post" action="{{ route('stock.store') }}">
      @csrf
      <div class="form-group">
        <label for="material_id">Seleccione nombre del material:</label>
        <select class="form-control" name="material_id">
          @foreach($materials as $material)
            <option value="{{ $material->id }}">{{$material->type->name}}</option>
          @endforeach
        </select>
      </div>
      <div class="form-group">
        <label for="serial">Número de serie:</label>
        <input type="text" class="form-control" name="serial"/>
      </div>
      <div class="form-group">
        <label for="expiration">Fecha de expiración:</label>
        <input type="date" class="form-control" name="expiration"/>
      </div>
      <a class="btn btn-default" href="{{ route('stock.index') }}"> Cancelar</a>
      <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
  </div>
</div>

@endsection

resources/views/stock/editar.blade.php
@extends('dashboard')

@section('content')

<div class="box box-solid box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Editar Modelo</h3>
    <div class="box-tools pull-right">
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <form method="post" action="{{ route('materiales.update', $material->id) }}">
      @method('PATCH')
      @csrf
      <div class="form-group">
        <label for="name">Nombre del material:</label>
        <input type="text" class="form-control" name="name" value="{{ $material->name }}"/>
      </div>
      <div class="form-group">
        <label for="key">Clave:</label>
        <input type="text" class="form-control" name="key" value="{{ $material->key }}"/>
      </div>
      <div class="form-group">
        <label for="unit">Cantidad:</label>
        <input type="number" class="form-control" name="unit" value="{{ $material->unit }}"/>
      </div>
      <div class="form-group">
        <label for="code">Código:</label>
        <input type="number" class="form-control" name="code" value="{{ $material->code }}"/>
      </div>
      <div class="form-group">
        <label for="description">Descripción:</label>
        <textarea class="form-control" rows="5" name="description">{{ $material->description }}</textarea>
      </div>
      <div class="form-group">
        <label>Seleccione marca:</label>
        <select class="form-control" name="brand_id">
          @foreach($brands as $brand)
            @if($brand->id == $material->brand_id)
              <option selected value="{{ $brand->id }}" >{{ $brand->name }}</option>
            @else
              <option value="{{ $brand->id }}" >{{ $brand->name }}</option>
            @endif
          @endforeach
        </select>
      </div>
      <div class="form-group">
        <label>Seleccione marca:</label>
        <select class="form-control" name="exemplar_id">
          @foreach($exemplars as $exemplar)
            @if($exemplar->id == $material->exemplar_id)
              <option selected value="{{ $exemplar->id }}" >{{ $exemplar->name }}</option>
            @else
              <option value="{{ $exemplar->id }}" >{{ $exemplar->name }}</option>
            @endif
          @endforeach
        </select>
      </div>
      <a class="btn btn-default" href="{{ route('materiales.index') }}"> Cancelar</a>
      <button type="submit" class="btn btn-primary">Actualizar</button>
    </form>
  </div>
</div>

@endsection

resources/views/stock/index.blade.php
@extends('dashboard')

@section('content')

<div class="box box-solid box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Almacén</h3>
    <div class="box-tools pull-right">
      <a class="btn btn-success fa fa-plus" href="{{ route('stock.create') }}"> Agregar</a>
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  {{--<form action="{{ route('materiales.destroy', $material->id) }}" method="POST">--}}
    <div class="box-body">
      {{--<div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label for="area_id">Seleccione categoría:</label>
            <select class="form-control" name="area_id">
              @foreach($categories as $category)
                <option value="{{ $category->id }}">{{$category->name}}</option>
              @endforeach
            </select>
          </div>
        </div>
      </div>--}}
      <table class="table table-striped">
        <thead>
            <tr>
              <td>ID</td>
              <td>Nombre del material</td>
              <td>Número de serie</td>
              <td>Unidad</td>
              <td>Marca</td>
              <td>Modelo</td>
              <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
          @foreach($stocks as $stock)
            <tr>
              <td>{{$stock->id}}</td>
              <td>{{$stock->material->type->name}}</td>
              <td>{{$stock->serial}}</td>
              <td>{{$stock->material->unit->name}}</td>
              <td>{{$stock->material->brand->name}}</td>
              <td>{{$stock->material->model}}</td>
              <td>
                <form action="{{ route('stock.destroy', $stock->id) }}" method="POST">
                  <a class="btn btn-info fa fa-eye" href="{{ route('stock.show',$stock->id) }}"></a>
                  <a class="btn btn-primary fa fa-pencil" href="{{ route('marcas.edit',$stock->id) }}"></a>
                  @csrf
                  @method('DELETE')
                    <button class="btn btn-danger fa fa-trash" type="submit"></button>
                </form>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      {!! $stocks->links() !!}
    </div>
  {{-- </form> --}}
</div>

@endsection

resources/views/stock/show.blade.php
@extends('dashboard')

@section('content')

<div class="box box-solid box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Material en stock</h3>
    <div class="box-tools pull-right">
      {{--<a class="btn btn-success fa fa-plus" href="{{ route('stock.create') }}"> Agregar</a>--}}
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <div class="row">
      <div class="col-xs-6">      
        <div class="form-group">
          <strong>Nombre del material:</strong>
            </br>
            {{ $itemStock->material->type->name }}
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <strong>Número de serie:</strong>
            </br>
            {{ $itemStock->serial }}
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <strong>Unidad:</strong>
            </br>
            {{ $itemStock->material->unit->name }}
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <strong>Marca:</strong>
            </br>
            {{ $itemStock->material->brand->name }}
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <strong>Modelo:</strong>
            </br>
            {{ $itemStock->material->model }}
        </div>
      </div>
      <div class="col-xs-3">
        <div class="form-group">
          <strong>Imagen:</strong>
            </br>
            <img class="small" src="{{ asset('img/'.$itemStock->material->image) }}">
        </div>
      </div>
      <div class="col-xs-3">
        <div class="form-group">
          <strong>Código QR:</strong>
            </br>
            <img src="data:image/png;base64, 
              {!! base64_encode(QrCode::format('png')
                ->encoding('UTF-8')
                ->size(150)
                ->generate(
                  'Nombre del material: '.$itemStock->material->type->name.', '.
                  'Número de serie: '.$itemStock->serial.' , '.
                  'Unidad de medida: '.$itemStock->material->unit->name.', '.
                  'Marca: '.$itemStock->material->brand->name.' , '.
                  'Modelo: '.$itemStock->material->model)
              )!!} ">
        </div>
      </div>
    </div>
    <a class="btn btn-default" href="{{ route('stock.index') }}"> Cerrar</a>
  </div>
</div>

@endsection